### ISSUE TITLE
what kind of format should motif.txt be if I have  more than 1 motif ? 2.0version

### ISSUE THREAD

**Issue by mooerccx** [fallandar/cysmotifsearcher#3] opened 2021-04-01 03:34 UTC
hello, recently I hope to use this software to search for motifs，I found that it works well when there is only one motif in the motif.txt , when it comes to more than 1, the program will only search for the previous one，I think this may be my format is wrong，Hope you can point out my mistake，thanks！ Below is the content of my file：
YX{0,10}CX{7,13}CX{2,6}CX{0,5}RX{0,10}C
YX{0,7}CX{0,5}GX{1,6}CX{0,5}S{0,10}CX{1,8}CX{0,4}RX{0,10}C
YX{0,10}CX{0,13}G{0,13}CX{0,6}CX{0,5}RX{0,10}C

**Comment by fallandar** [comment] 2021-04-02 22:42
Hi! Thanks for using my program. 
Current version of Cysmotif searcher is 3.3.1, and the version 2.0 has not ever been uploaded to github. So I will consider you are using the latest version.

Your format is not wrong, and the program should search for all motifs present in the file. Does it work for each of your three motifs separately or only for the one you put first (YX{0,10}CX{7,13}CX{2,6}CX{0,5}RX{0,10}C) ? Are the motifs missing at the final stage of filtration or even at the initial stage?

**Can you please provide me an exemplary sequence in which two or more of your motifs exist? It is very hard to track the error without having some input data. In addition, please specify the exact command line of Cysmotif searcher call with all the parameters you have used.**

Also,  you have come across the current limitation of Cysmotif searcher. The problem is that 'X' expands to 'any amino acid except C', or, according to regex syntax, to [ABD-Z]. In your third motif you have, for example, CX{0,13}G{0,13}C. Since X also includes G, this expression does not work as you probably intended it to work. Let's change 13 to 3 for simplicity and consider the pattern CX{0,3}G{0,3}C. It will match, for example, CAGGGGGC (that is, 5 G's), If this is what you wanted, then all is fine.

In addition, I would not recommend using zero quantifiers since they make a motif too general to be useful. For example, CX{0,13}G{0,13}C will match CC, CAC, CAGC etc. But the cases of having nothing between two cysteines and having something are very different from the point of possible peptide conformation and function. However, if you really want to use them, this will not violate any rules and the program should search for such a motif without any complaints.

I am waiting for additional data from you and I hope that I will provide you better answer when I have these data.

**Comment by fallandar** [comment] 2021-04-05 22:09
> 
> 
> hello, recently I hope to use this software to search for motifs，I found that it works well when there is only one motif in the motif.txt , when it comes to more than 1, the program will only search for the previous one，I think this may be my format is wrong，Hope you can point out my mistake，thanks！ Below is the content of my file：
> YX{0,10}CX{7,13}CX{2,6}CX{0,5}RX{0,10}C
> YX{0,7}CX{0,5}GX{1,6}CX{0,5}S{0,10}CX{1,8}CX{0,4}RX{0,10}C
> YX{0,10}CX{0,13}G{0,13}CX{0,6}CX{0,5}RX{0,10}C

Put on hold. Waiting for additional data to be provided.

**Comment by mooerccx** [comment] 2021-04-07 14:23
Thank you very much for your answer, based on the answer you gave, I solved my problem! The program I used was used in your article published in 2015, and the version is 2.0. Unfortunately, I encountered another problem when using the 2.0 version of the program. I hope you can give me some guidance. The program cannot call the Signalp software normally. In the final result, the number of sequences with signal peptides is always 0, even if there are sequences that meet the requirements. The result is very strange. If necessary, I can send all the files used by email to you

**Comment by fallandar** [comment] 2021-04-08 17:22
Is there particular reason for using older version? Some bugs could be already fixed in 3.3.1. It has the same parameters and will not require making any additional investigations to run it.

However, I can imagine the following possible reasons for errors when using SignalP:
- the path to signalp executable should be specified in the beginning of a script manually ($signalp="your_path";). Otherwise, the script simply will not find signalP.
- what version of signalP do you use? Old script is compatible only with version 4. New (3.3.1 version) script is also compatible with signalp 5.

If these suggestions will not help, please send me the files (fallandar@gmail.com)  and I will check them. Please also specify the parameters of a script call.
> 
> Thank you very much for your answer, based on the answer you gave, I solved my problem! The program I used was used in your article published in 2015, and the version is 2.0. Unfortunately, I encountered another problem when using the 2.0 version of the program. I hope you can give me some guidance. The program cannot call the Signalp software normally. In the final result, the number of sequences with signal peptides is always 0, even if there are sequences that meet the requirements. The result is very strange. If necessary, I can send all the files used by email to you

**Closed as completed** 2021-04-19 13:38 UTC
